### ISSUE TITLE
[Char Gen] Step 8: choose languages

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#104]
the eigth prompt / or part of the prompt shall contain the option to choose languages

the user shall have the option to chose languages for the character. 
~the languages from the config shall be listed as options.~ see comment

~per default Dwarven and the respective namegiver shall be highlighted.~ see comment

~there shall be 2 points for spoken and 1 point for read/write~see skills

the Confirm Prompt will lead to the next step: #103 

Prompt Options:
Confirm
Cancel
Close

**Comment by ChristopherSD** [comment]
Same here as with the starting equipment for PCs. It would be useful to have the language talents in a pack as a base thing, so we can add it to the PC automatically. @patrickmohrmann

**Comment by patrickmohrmann** [comment]
ich hatte noch eine idee bezüglich der sprachen. 

ich hab mir gedacht, dass wir jedem Actor in Phase 1 erstmal die Standard Sprachen mitgeben in einer liste zum Ankreuzen. 
lesen/Schreiben --- Sprechen
[] Zwergisch ---- [ ] Zwergisch 
[] Elfisch---- [ ] Elfisch 

so

im zweiten schritt irgendwann als feature, dann eine Möglichkeit pro Actor, die liste manuell zu erweitern. Sprich einen kleinen  button wo man einen freitext eintragen kann und der Taucht dann einfach in der liste mit auf, inklusive einem delete button. Das sollten wir alles in einem Object unterbringen können denke ich

"Language": {
   "speak": {
      "dwarven": true,
      "elven": true,
      "ork": false, 
     },
    "read": {
      "dwarven": true,
      "elven": true,
      "ork": false, 
     }
  }


ich denke dein Einwand mit die spieler können selber nachschauen wie viele sprachen sie können etc. ist völlig legitim

dann müssen wir uns darum nicht kümmern und können in der Char gen einfach die defaults mit angeben.

ich würd auch noch ein feature einbauen in dem man später als GM noch weitere standard sprachen im setting mit eintragen kann.

**Comment by ChristopherSD** [comment]
Closed with #736
