### ISSUE TITLE
[Char Gen] Step 10: add basic equipment +100 silver

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#105]
the tenth prompt / or part of the prompt shall only show the starting equipment which will be added to the actor

![image](https://github.com/patrickmohrmann/earthdawn4eV2/assets/76265425/a363f67f-a9e6-434e-88e4-4c4b90c1350f)

the Confirm Prompt will finish the character creation

Prompt Options:
Confirm
Cancel
Close

**Comment by ChristopherSD** [comment]
Adding items is only possible if they are created or exist already. In this case it would be useful if we had the listed items in a pack that is shipped with the system. But we probably need to clarify that with FASA first, right @patrickmohrmann ?

**Comment by patrickmohrmann** [comment]
I asked fasa again, it sometimes takes several reminder to get an answer

**Comment by patrickmohrmann** [comment]
we can create basic items etc. to create a standard compendium
