### ISSUE TITLE
Enhance {{toFormGroup}} helper to work with Mapping fields

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#1081]
**Description**
the helper formInput and formFields shall work with mappingFields (e.g. defenses or attributes)

**Additional context**

**Comment by ChristopherSD** [comment]
This requires implementation of the abstract `DataField` methods [`toInput`](https://foundryvtt.com/api/classes/foundry.data.fields.DataField.html#toInput) and [`toFormGroup`](https://foundryvtt.com/api/classes/foundry.data.fields.DataField.html#toFormGroup) inthe MappingField class.
