### ISSUE TITLE
Trigger Attribute Test

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#235]
**Description**
attribute tests shall be triggered by clicking on the dice symbol, which appears on a mouse over on the respective attribute.

**Comment by ChristopherSD** [comment]
@patrickmohrmann 
Currently the dice symbol only appears onHovering the attribute label. so it is not clickable, since it disappears when trying to move the cursor over it. When the functionality is done, can you correct that?

**Comment by patrickmohrmann** [comment]
> @patrickmohrmann Currently the dice symbol only appears onHovering the attribute label. so it is not clickable, since it disappears when trying to move the cursor over it. When the functionality is done, can you correct that?

I hope so, but something will be possible of course
