### ISSUE TITLE
[Suggestion] Rename folder name for "global-templates"

### ISSUE THREAD

**Issue by ChristopherSD** [patrickmohrmann/earthdawn4eV2#309]
To keep paths short, concise and for consistency: rename the folder `ed4e/templates/global-templates` to `ed4e/templates/global`

**Comment by ChristopherSD** [comment]
@patrickmohrmann should I do it? It's basically 2 clicks in my IDE...

**Comment by patrickmohrmann** [comment]
yes please if its only two clicks perfect @ChristopherSD
