### ISSUE TITLE
pre-localize the config

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#325]
![image](https://github.com/patrickmohrmann/earthdawn4eV2/assets/76265425/5cddf311-36a3-4651-b67e-202d2886bb91)

@ChristopherSD I'm not 100% sure what this means, but it seems legit to do it.

- [ ] revisit the templates\actor\character-details\details-general.hbs and change the handlebars helper lookup after the pre-localization.

**Comment by ChristopherSD** [comment]
@patrickmohrmann 
I think I know what they mean. Actually already thought about doing that.
Will take care of it!
