### ISSUE TITLE
Languages during character generation

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#593]
**Description**
Speak Language and Read/ write Language are available for all characters. 

speak language has a minimum of 2 points and speak language a min of 1 point, (those are free points.

The skill items will be enhanced by two details. 
speak language and read/write language. both are checkboxes and will resemble these skills. 
the char gen will search for skills with these checked.

a field with all Languages shall be available to select the required once

**Additional context**

**Comment by ChristopherSD** [comment]
Closed with #736
