### ISSUE TITLE
Pools don't persist data

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#594]
**Describe the bug**
world or compendium items, do have the problem, that the abilities drawn to the pools are not persisted. after a refresh the pools are empty again

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ChristopherSD** [comment]
context: ability pools in advancement data on discipline items
