### ISSUE TITLE
Attribute left over max 2

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#598]
**Description**
the maximum attribute leftover is 2 to gain more karma

**Additional context**

**Comment by ChristopherSD** [comment]
Is that confirmed? The players guide only says this:
> Unused Attribute Points
> Sometimes, a player will have leftover Attribute Points after purchasing his character’s Attribute values. Any unused Attribute Points convert into additional Maximum Karma at a one-to-one ratio. See Karma, p. 37, for more information.
> Note that this is one-way; you can not sacrifice Maximum Karma to gain additional Attribute Points.

The only restriction with 2 in it I can find is the lowering of attribute values to get extra points. But nothing about additional Attribute points.

**Comment by ChristopherSD** [comment]
As per answer in the FASA discord vom 3 Jub jubs in an Espagra cloak:
"there is no cap to how much you can screw up your character
there is a cap to how much you can lower an attribute from the starting value (that's 2)"

So, closed..
