### ISSUE TITLE
Create Standard Items 1 (for Char Gen)

### ISSUE THREAD

**Issue by patrickmohrmann** [patrickmohrmann/earthdawn4eV2#693]
**Description**
after Fasa Agreed on the usage / inclusion of items, like read/write skills, basic equipment etc. those will be placed in a separate Compendium

Speak Language JSON
`{"type":"skill","name":"Speak Language","system":{"difficulty":{"target":"none","group":"none","fixed":0},"description":{"value":"<p>The character learns to communicate with others in different languages. Language skills allow a character to speak, read, and write different languages.</p><p>All characters begin the game with ranks in the Speak Language skill. Each rank represents a language the character knows.</p><p>Learning new languages differs slightly from the process of learning other skills.</p><p>To learn a new language, the character increases his rank in the appropriate skill. He then spends at least one month studying the language with a teacher or native speaker. At the end of this time, he makes a skill test against the Learning Difficulty of the language. If successful, he learns the language. If the test fails, he may make an additional attempt after studying the language for another month.</p><p>The Learning Difficulty for the different racial languages is shown in the Language Table. The numbers reflect the difficulty of learning the base “racial” versions of these languages.</p><p>Dialects are considered different languages for the purposes of this talent (see below). When speaking a language learned through this talent, the adept makes a Speak Language test against the Learning Difficulty of the language. The success level determines how well they communicate.</p><p>Simple sentences or ideas, such as “Which way to the sheriff?” may only require a single success; normal conversation that includes idioms or jargon require two; technical conversations or other discussions filled with specialized jargon require three successes; conversations about philosophy, or other abstract ideas, may require four or more. Partial successes may convey more or less detail at the gamemaster’s discretion.</p><p>The effect of each test lasts for a number of hours equal to the adept’s Speak Language rank, allowing communication at the level achieved by the test result. If the adept requires more complex conversation, he must make another Speak Language test.</p><p></p><h3>Dialects </h3><p>Languages are often complex and most possess many different variations, called dialects. These dialects are sometimes regional, others by city, or even by kaer. The Learning Difficulty of a dialect is based on the original language, usually the base DN +2, but higher difficulties are possible. The adept must know how to speak the base language before he can attempt to learn a dialect of that language. If the adept knows the base language of a dialect, he can communicate, but his ability to do so may be limited at the gamemaster’s discretion.</p>"},"action":"standard","strain":0,"attribute":"per","source":{"class":null,"tier":"novice"},"level":0,"skillType":"general"},"img":"icons/svg/item-bag.svg","effects":[]}`

**Comment by ChristopherSD** [comment]
Standard items relevant for char gen will now be created during char gen itself. This avoids the need for compendia handling and makes localization easier.
The compendia with basic items should still be created. @patrickmohrmann would you create a new issue unrelated to char gen for that?

**Comment by patrickmohrmann** [comment]
issue is created see #980
